name: Release to Edge
on:
  push:
    branches:
      - main

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@1.0.1-rc
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run static analysis (charm)
        run: tox -vve static-charm
      - name: Run static analysis (unit tests)
        run: tox -vve static-unit
      - name: Run static analysis (integration tests)
        run: tox -vve static-integration

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -vve lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -vve unit

  integration-test:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          lxd-channel: 4.0/stable
      - name: Run lma-rules integration tests
        run: tox -vve integration

  release-to-charmhub:
    name: Release to CharmHub
    needs:
      - static-analysis
      - lint
      - unit-test
      - integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@1.0.1-rc
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1.0.1-rc
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"
